import { readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { compile } from "@vue/compiler-dom"

const TEMPLATE_START = '<template id="app-template">'
const TEMPLATE_END = "</template>"

function normalize(value: string): string {
  return `${value.replaceAll("\r\n", "\n").replace(/[ \t]+$/gm, "").trimEnd()}\n`
}

function templateFromPage(page: string): string {
  const start = page.indexOf(TEMPLATE_START)
  const end = page.lastIndexOf(TEMPLATE_END)
  if (start < 0 || end <= start) throw new Error("The administrator template markers are missing or malformed")
  return page.slice(start + TEMPLATE_START.length, end).trim()
}

function compiledRender(template: string): string {
  const result = compile(template, {
    mode: "function",
    hoistStatic: true,
    cacheHandlers: false,
    comments: false
  })
  const assignment = result.code.replace("return function render", "window.NeuralwattRender = function render")
  if (assignment === result.code) throw new Error("Vue did not emit the expected render function")
  const indented = assignment.split("\n").map((line) => `  ${line}`).join("\n")
  return normalize(`/* Generated by scripts/compile-admin-ui.ts. */
/* global Vue */
(() => {
${indented}
})()`)
}

async function assertCurrent(path: string, expected: string): Promise<void> {
  let actual: string
  try {
    actual = normalize(await readFile(path, "utf8"))
  } catch {
    throw new Error(`${path} is missing; run pnpm run ui:compile`)
  }
  if (actual !== expected) throw new Error(`${path} is stale; run pnpm run ui:compile`)
}

async function main(): Promise<void> {
  const root = resolve(import.meta.dirname, "..")
  const pagePath = resolve(root, "server", "ui", "index.html")
  const renderPath = resolve(root, "public", "vendor", "admin-render.js")
  const runtimeSourcePath = resolve(root, "node_modules", "vue", "dist", "vue.runtime.global.prod.js")
  const runtimePath = resolve(root, "public", "vendor", "vue.runtime.global.prod.js")
  const page = await readFile(pagePath, "utf8")
  const render = compiledRender(templateFromPage(page))
  const runtime = normalize(await readFile(runtimeSourcePath, "utf8"))

  if (process.argv.includes("--check")) {
    await assertCurrent(renderPath, render)
    await assertCurrent(runtimePath, runtime)
    return
  }
  await writeFile(renderPath, render, "utf8")
  await writeFile(runtimePath, runtime, "utf8")
}

main().catch((error: unknown) => {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
  process.exitCode = 1
})
